### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot use object of type Holiday as array

### ISSUE THREAD

**Issue by flegastelois** [DIOHz0r/holidays#1]
```txt
PHP Fatal error:  Uncaught Error: Cannot use object of type Holiday as array in /var/www/flyve-mdm/erp-import/lib/DIOHz0r/Holidays/AbstractHoliday.php:178
Stack trace:
#0 /var/www/flyve-mdm/erp-import/lib/DIOHz0r/Holidays/AbstractHoliday.php(210): Holidays\AbstractHoliday->isHoliday('2018-09-13')
#1 /var/www/flyve-mdm/erp-import/inc/date.function.php(46): Holidays\AbstractHoliday->isValidDate('2018-09-13')
#2 /var/www/flyve-mdm/erp-import/import.php(196): countWorkdays('2018-09-13 09:0...', '2018-09-13 18:0...')
#3 {main}
  thrown in /var/www/flyve-mdm/erp-import/lib/DIOHz0r/Holidays/AbstractHoliday.php on line 178
```

https://github.com/DIOHz0r/holidays/blob/4355c7e48f4336ea62a5378766ce6986e8ac60bb/src/Holidays/AbstractHoliday.php#L197

**$this['month']** must be replaced by **$holiday['month']**

**Comment by DIOHz0r** [comment]
I've updated the code with your help. Thank you
